# -*- coding: utf-8 -*-
"""Data Manipulation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dnbNHRyDzukEq2IVv2Bx2tdzVEbLZJc0
"""

import pandas as pd

df1 = pd.read_csv("district_school_data.csv")
df2 = pd.read_csv("district_expense_data.csv")
d = {'District': [], 'County': [], 'Students':[], 'Graduation Rate':[], 'Cost':[]}
df3 = pd.DataFrame(data=d)

for i1, row1 in df1.iterrows():
  for i2, row2 in df2.iterrows():
    if row1['District'] == row2['DISTRICT']:
      dprime = {'District': [row1['District']], 'County': [row1['County']], 'Students':[row1['Students']], 'Graduation Rate':[row1['Grad Rate']], 'Cost':[row2[' EDP 365 ']]}
      df4 = pd.DataFrame(data=dprime)
      df3 = df3.append(df4)
df3.to_csv("district_data.csv")

print(len(df3))

print(df3)